In [4]:
import numpy as np

scores = np.array([1,2,3,4,5,6,7,8,9])
print("shape: ",  scores.shape)
print("ndim: ", scores.ndim)
print("dtype: ", scores.dtype)


shape:  (9,)
ndim:  1
dtype:  int64


In [6]:
data = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
])

print(data)
print("shape: ",  data.shape)
print("ndim: ", data.ndim)
print("dtype: ", data.dtype)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
shape:  (3, 3)
ndim:  2
dtype:  int64


In [7]:
arr = np.array([1,2,3,4,5])
print("First item: ", arr[0])

First item:  1


In [10]:
m = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
# row 0:
print(m[0])
# column 1:
print(m[:, 1])

[10 20 30]
[20 50 80]


In [12]:
scores = np.array([1,2,3])
print(scores + 1)
print(scores *2)
print( scores /2) 

[2 3 4]
[2 4 6]
[0.5 1.  1.5]


In [13]:
lst_scores = [1,2,3]
print(lst_scores * 2) 

[1, 2, 3, 1, 2, 3]


In [17]:
scores = np.array([1,2,3])
print(scores.sum())
print(scores.min())
print(scores.max())
print(scores.mean())

6
1
3
2.0


In [18]:
scores = np.array([7, 8, 9, 10, 6])

mask = scores >= 8
print("mask:", mask)
print("filtered:", scores[mask])

mask: [False  True  True  True False]
filtered: [ 8  9 10]


In [19]:
print(scores[scores >= 8])

[ 8  9 10]


In [20]:
print(scores[scores % 2 == 0])

[ 8 10  6]


In [21]:
scores = np.array([7, 8, 9, 10, 6])

# 1) cộng bonus 0.5 điểm
bonus_scores = scores + 0.5

# 2) lọc các bạn >= 8.5 sau bonus
passed = bonus_scores[bonus_scores >= 8.5]

# 3) thống kê
print("bonus_scores:", bonus_scores)
print("passed:", passed)
print("pass_count:", passed.size)
print("pass_mean:", passed.mean())

bonus_scores: [ 7.5  8.5  9.5 10.5  6.5]
passed: [ 8.5  9.5 10.5]
pass_count: 3
pass_mean: 9.5


In [22]:
temps = np.array([28, 30, 31, 29, 27, 32])
print(temps.shape)
print(temps.ndim)
print(temps.dtype)

(6,)
1
int64


In [26]:
print(temps[:3])
print(temps[-2:])
print(temps[::2])

[28 30 31]
[27 32]
[28 31 27]


In [30]:
temps_f = (temps*9/5) + 32
print(temps_f)

[82.4 86.  87.8 84.2 80.6 89.6]


In [31]:
print(temps[temps>= 30])

[30 31 32]


In [32]:
print(temps.mean())
print(temps.max())
print(temps.min())

29.5
32
27


In [38]:
# columns = [order_id, amount]
orders = np.array([
    [1, 200],
    [2, 120],
    [3, 450],
    [4, 150]
])

tmp = orders[orders[:,1] >= 150]
print(tmp)
print(tmp.mean())

[[  1 200]
 [  3 450]
 [  4 150]]
134.66666666666666
