In [1]:
import numpy as np

In [2]:
# zeros

print(np.zeros(5))
print()
print(np.zeros((2,3)))

[0. 0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# ones 
print(np.ones(10))
print(np.ones((2,3)))
print(np.ones((3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
# arrange 
print(np.arange(10))
print(np.arange(2, 10, 2))

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [5]:
a = np.arange(6)
print(a)
print(a.reshape(2, 3))
print(a.reshape(3,2))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [6]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([10, 20,30])
print(a + b) 

[[11 22 33]
 [14 25 36]]


In [7]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
col = np.array([10, 100, 1000])

print(a * col.reshape(3,1))


[[  10   20   30]
 [ 400  500  600]
 [7000 8000 9000]]


In [8]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Mảng gốc:")
print(A)
print("shape:", A.shape)

print(np.sum(A, axis = 0))
print(np.sum(A, axis = 1))
print(np.mean(A, axis = 0))
print(np.mean(A, axis = 1))

Mảng gốc:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
[12 15 18]
[ 6 15 24]
[4. 5. 6.]
[2. 5. 8.]


In [9]:
import numpy as np

# Dữ liệu mẫu 4x3
data = np.array([[85, 92, 78],
                 [60, 88, 45],
                 [95, 70, 82],
                 [55, 91, 67]])

print("Dữ liệu gốc:")
print(data)
mask = data>= 80
print(mask)
print(len(mask))
print(data * mask)

data_nan = np.where( mask, data, np.nan)
print(data_nan)

Dữ liệu gốc:
[[85 92 78]
 [60 88 45]
 [95 70 82]
 [55 91 67]]
[[ True  True False]
 [False  True False]
 [ True False  True]
 [False  True False]]
4
[[85 92  0]
 [ 0 88  0]
 [95  0 82]
 [ 0 91  0]]
[[85. 92. nan]
 [nan 88. nan]
 [95. nan 82.]
 [nan 91. nan]]


In [10]:
# Giả sử có dữ liệu nhiệt độ, muốn giữ chỉ nhiệt độ hợp lý (20-35°C)
nhiet_do = np.random.uniform(10, 40, (5, 7))   # 5 ngày x 7 giờ

mask_hop_ly = (nhiet_do >= 20) & (nhiet_do <= 35)

# Thay giá trị bất thường thành NaN
nhiet_do_sach = np.where(mask_hop_ly, nhiet_do, np.nan)

print("Nhiệt độ sau khi lọc:", nhiet_do_sach)

Nhiệt độ sau khi lọc: [[        nan 21.98092408         nan 29.13545019         nan 20.88595518
          nan]
 [        nan 33.6187903  26.87256328         nan 21.62005712 31.89902641
          nan]
 [        nan         nan 23.86242134 27.07420236 29.37599664 24.09270704
  21.97195219]
 [        nan         nan         nan 28.51542573 31.43243661         nan
  26.95862252]
 [        nan 28.32292081 24.91213614         nan 20.36743905 22.53339469
          nan]]


In [11]:
a = np.zeros((2, 3))
b = np.ones((2, 2))
c = np.arange(0, 10, 2)   # 0,2,4,6,8
d = np.arange(1, 13).reshape(3, 4)

print("a:\n", a)
print("b:\n", b)
print("c:", c)
print("d:\n", d)
print("d.shape:", d.shape)

a:
 [[0. 0. 0.]
 [0. 0. 0.]]
b:
 [[1. 1.]
 [1. 1.]]
c: [0 2 4 6 8]
d:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
d.shape: (3, 4)


In [12]:
revenue = np.array([
    [100, 120,  90],
    [ 80, 110, 130],
    [150, 140, 160]
])  # shape = (3, 3)

day_adjust = np.array([10, -5, 0])   # shape = (3,)

adjusted_by_day = revenue + day_adjust

print("revenue:\n", revenue)
print("day_adjust:", day_adjust)
print("adjusted_by_day:\n", adjusted_by_day)
print("shapes:", revenue.shape, day_adjust.shape, adjusted_by_day.shape)


store_bonus = np.array([5, 0, 10]).reshape(3, 1)   # shape = (3,1)

adjusted_by_store = revenue + store_bonus

print("store_bonus:\n", store_bonus)
print("adjusted_by_store:\n", adjusted_by_store)
print("shapes:", revenue.shape, store_bonus.shape)

revenue:
 [[100 120  90]
 [ 80 110 130]
 [150 140 160]]
day_adjust: [10 -5  0]
adjusted_by_day:
 [[110 115  90]
 [ 90 105 130]
 [160 135 160]]
shapes: (3, 3) (3,) (3, 3)
store_bonus:
 [[ 5]
 [ 0]
 [10]]
adjusted_by_store:
 [[105 125  95]
 [ 80 110 130]
 [160 150 170]]
shapes: (3, 3) (3, 1)


In [13]:
revenue = np.array([
    [100, 120,  90],
    [ 80, 110, 130],
    [150, 140, 160]
])

col_sum = revenue.sum(axis=0)   # tổng từng cột
row_sum = revenue.sum(axis=1)   # tổng từng hàng
row_mean = revenue.mean(axis=1)

print("col_sum (axis=0):", col_sum)
print("row_sum (axis=1):", row_sum)
print("row_mean (axis=1):", row_mean)

col_sum (axis=0): [330 370 380]
row_sum (axis=1): [310 320 450]
row_mean (axis=1): [103.33333333 106.66666667 150.        ]
